name: Deploy to GitHub Releases

on:
  push:
    tags:
      - '*'

env:
  PYINSTALLER_COMPILE_BOOTLOADER: 1

jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [windows-latest]
    steps:
    - name: Set env
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'
    - name: Rebranding
      shell: bash
      run: bash rebrand.sh
    - name: Install project
      shell: bash
      run: bash install.sh
    - name: Build windows executable
      if: runner.os == 'windows'
      working-directory: ./project/build-recipes
      run: |
        pip install -r win_build_requirements.txt
        pyinstaller -y --log-level=WARN win_CytoPlot.spec
        # Run the binary (the most simple test)
        dist\\CytoPlot\\CytoPlot.exe --version
        python win_make_iss.py
        ISCC.exe /Q win_cytoplot.iss
    - name: Build Documentation
      if: runner.os == 'windows'
      working-directory: ./project/docs
      shell: bash
      run: |
        pip install -r requirements.txt
        sed -i '/sec_getting_started/d' index.rst
        sed -i '/sec_changelog/d' index.rst
        sed -i '/sec_imprint/d' index.rst
        python -m sphinx -T -b latex -d _build/doctrees -D language=en . _pdf
        cd _pdf
        latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=CytoPlot-Documentation -interaction=nonstopmode
    - name: Release Assets
      uses: softprops/action-gh-release@v1
      with:
        name: CytoPlot ${{ env.RELEASE_VERSION }}
        draft: true
        prerelease: false
        body: |
            ![](https://img.shields.io/github/downloads/Rivercyte/CytoPlot/${{ env.RELEASE_VERSION }}/total.svg)
        files: |
          ./project/build-recipes/dist/*.dmg
          ./project/build-recipes/dist/*.pkg
          ./project/build-recipes/Output/*.exe
          ./project/docs/_pdf/*.pdf
